/**
 * Report Generator Module
 * 
 * Generates markdown reports and visualizations
 */

import * as fs from 'fs';
import * as path from 'path';

export class ReportGenerator {
  private projectRoot: string;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
  }

  /**
   * Generate all reports
   */
  async generate(snapshot: any, trends: any, comparison: any): Promise<void> {
    // Generate weekly snapshot report
    await this.generateWeeklySnapshot(snapshot, trends, comparison);
    
    // TODO: Generate monthly report (if first Saturday of month)
    // TODO: Generate quarterly report (if first Saturday of quarter)
  }

  /**
   * Generate weekly snapshot report
   */
  private async generateWeeklySnapshot(snapshot: any, trends: any, comparison: any): Promise<void> {
    const timestamp = new Date();
    const dateStr = this.formatDate(timestamp);
    const reportsDir = path.join(__dirname, '..', 'reports', dateStr);
    
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    const report = this.generateWeeklyMarkdown(snapshot, trends, comparison);
    
    fs.writeFileSync(
      path.join(reportsDir, 'WEEKLY_ANALYSIS.md'),
      report
    );
  }

  /**
   * Generate weekly markdown report
   */
  private generateWeeklyMarkdown(snapshot: any, trends: any, comparison: any): string {
    const week = snapshot.week || 0;
    const year = snapshot.year || new Date().getFullYear();

    return `# Weekly Analytics Report
**Agent 11: Data Analytics & Comparison Specialist**  
**Week ${week}, ${year}**  
**Generated:** ${new Date(snapshot.timestamp).toLocaleString()}

## Executive Summary

### Key Metrics

| Metric | Value | Status |
|--------|-------|--------|
| Guard Rails Added | ${snapshot.metrics?.guard_rails?.added || 0} | ${snapshot.metrics?.guard_rails?.added > 0 ? '✅' : '➖'} |
| Issues Found | ${snapshot.metrics?.validation?.issues_found || 0} | ${snapshot.metrics?.validation?.issues_found === 0 ? '✅' : '⚠️'} |
| Issues Fixed | ${snapshot.metrics?.validation?.issues_fixed || 0} | ${snapshot.metrics?.validation?.issues_fixed === snapshot.metrics?.validation?.issues_found ? '✅' : '⚠️'} |
| Guard Rail Overhead | ${snapshot.metrics?.guard_rails?.overhead_ms || 0}ms | ${(snapshot.metrics?.guard_rails?.overhead_ms || 0) < 10 ? '✅' : '⚠️'} |

### Week-over-Week Comparison

${snapshot.comparison?.vs_last_week ? `
- **Performance**: ${snapshot.comparison.vs_last_week.performance_delta}
- **Issues**: ${snapshot.comparison.vs_last_week.issues_delta}
- **Coverage**: ${snapshot.comparison.vs_last_week.coverage_delta || 'N/A'}
` : 'No historical data available for comparison'}

## Trend Analysis

${trends.insights && trends.insights.length > 0 ? trends.insights.map((insight: string) => `- ${insight}`).join('\n') : 'No significant trends detected'}

## Recommendations

${snapshot.recommendations && snapshot.recommendations.length > 0 ? snapshot.recommendations.map((rec: string) => `- ${rec}`).join('\n') : 'No recommendations at this time'}

## Guard Rails Validated

${snapshot.metrics?.guard_rails?.validated ? snapshot.metrics.guard_rails.validated.map((v: string) => `- ${v}`).join('\n') : 'None'}

## Performance Metrics

${snapshot.metrics?.performance ? `
| Metric | Value |
|--------|-------|
| API Response Time | ${snapshot.metrics.performance.api_response_ms || 'N/A'}ms |
| Workflow Execution | ${snapshot.metrics.performance.workflow_execution_ms || 'N/A'}ms |
| Database Query | ${snapshot.metrics.performance.database_query_ms || 'N/A'}ms |
| Browser Operations | ${snapshot.metrics.performance.browser_operation_ms || 'N/A'}ms |
` : 'No performance metrics available'}

## Quality Metrics

${snapshot.metrics?.quality ? `
- **Test Coverage**: ${snapshot.metrics.quality.test_coverage || 'N/A'}
- **Errors Caught**: ${snapshot.metrics.quality.errors_caught || 0}
- **Silent Failures Prevented**: ${snapshot.metrics.quality.silent_failures_prevented || 0}
` : 'No quality metrics available'}

## Alerts

${snapshot.alerts && snapshot.alerts.length > 0 ? snapshot.alerts.map((alert: any) => {
  const icon = alert.level === 'critical' ? '🔴' : alert.level === 'warning' ? '⚠️' : 'ℹ️';
  return `${icon} **${alert.level.toUpperCase()}**: ${alert.message}`;
}).join('\n') : 'No alerts'}

---

*Generated by Agent 11: Data Analytics & Comparison Specialist*
`;
  }

  /**
   * Format date for file names
   */
  private formatDate(date: Date): string {
    return date.toISOString().split('T')[0].replace(/-/g, '');
  }
}
