/**
 * Context-Memory Intelligence Layer - Type Definitions
 *
 * Provides TypeScript interfaces for entity tracking, workflow history,
 * and adaptive learning across the workstation automation system.
 */

/**
 * Entity represents a tracked object across workflow executions
 * Can be files, repositories, issues, pull requests, agents, etc.
 */
export interface Entity {
  id: string;
  type:
    | "file"
    | "repository"
    | "issue"
    | "pr"
    | "agent"
    | "workflow"
    | "user"
    | "custom";
  name: string;
  metadata: Record<string, unknown>;
  first_seen: string;
  last_seen: string;
  access_count: number;
  context: EntityContext;
  tags: string[];
}

/**
 * Entity context provides semantic understanding
 */
export interface EntityContext {
  description?: string;
  relationships: EntityRelationship[];
  importance_score: number; // 0-100
  last_modified_by?: string;
  workflow_ids: string[];
}

/**
 * Relationship between entities
 */
export interface EntityRelationship {
  entity_id: string;
  relationship_type:
    | "depends_on"
    | "modifies"
    | "created_by"
    | "used_by"
    | "related_to";
  strength: number; // 0-1
  created_at: string;
}

/**
 * Workflow execution history record
 */
export interface WorkflowHistoryRecord {
  id: string;
  workflow_id: string;
  execution_id: string;
  started_at: string;
  completed_at?: string;
  duration_ms?: number;
  status: "success" | "failure" | "partial" | "cancelled";
  metrics: ExecutionMetrics;
  entities_accessed: string[];
  error_message?: string;
  retry_count: number;
}

/**
 * Performance and quality metrics for workflow execution
 */
export interface ExecutionMetrics {
  task_count: number;
  tasks_completed: number;
  tasks_failed: number;
  average_task_duration_ms: number;
  resource_usage?: {
    cpu_percent?: number;
    memory_mb?: number;
  };
  quality_score?: number; // 0-100
}

/**
 * Pattern detected from historical workflow executions
 */
export interface WorkflowPattern {
  id: string;
  pattern_type:
    | "success_sequence"
    | "failure_point"
    | "performance_bottleneck"
    | "optimization_opportunity";
  description: string;
  confidence: number; // 0-1
  occurrences: number;
  first_detected: string;
  last_detected: string;
  workflow_ids: string[];
  recommendation?: string;
}

/**
 * Learning model state for adaptive improvements
 */
export interface LearningModel {
  id: string;
  model_type:
    | "workflow_optimization"
    | "error_prediction"
    | "resource_allocation"
    | "task_sequencing";
  version: number;
  trained_at: string;
  accuracy: number; // 0-1
  training_samples: number;
  parameters: Record<string, unknown>;
  performance_history: PerformanceSnapshot[];
}

/**
 * Performance snapshot for model evaluation
 */
export interface PerformanceSnapshot {
  timestamp: string;
  accuracy: number;
  precision?: number;
  recall?: number;
  f1_score?: number;
  sample_count: number;
}

/**
 * Suggestion generated by learning model
 */
export interface LearningModelSuggestion {
  id: string;
  suggestion_type:
    | "workflow_optimization"
    | "error_prevention"
    | "resource_tuning"
    | "sequence_improvement";
  description: string;
  confidence: number; // 0-1
  estimated_impact: {
    time_savings_ms?: number;
    error_reduction_percent?: number;
    resource_savings_percent?: number;
  };
  workflow_id?: string;
  actionable: boolean;
  auto_apply: boolean;
  created_at: string;
  applied_at?: string;
  feedback?: SuggestionFeedback;
}

/**
 * Feedback on applied suggestions
 */
export interface SuggestionFeedback {
  applied: boolean;
  helpful: boolean;
  actual_impact: {
    time_change_ms?: number;
    error_change_percent?: number;
    resource_change_percent?: number;
  };
  user_comment?: string;
  recorded_at: string;
}

/**
 * Query options for entity store
 */
export interface EntityQueryOptions {
  type?: Entity["type"];
  tags?: string[];
  min_importance?: number;
  workflow_id?: string;
  limit?: number;
  offset?: number;
  sort_by?: "importance" | "access_count" | "last_seen";
  sort_order?: "asc" | "desc";
}

/**
 * Query options for workflow history
 */
export interface WorkflowHistoryQueryOptions {
  workflow_id?: string;
  status?: WorkflowHistoryRecord["status"];
  start_date?: string;
  end_date?: string;
  limit?: number;
  offset?: number;
  include_metrics?: boolean;
}

/**
 * Configuration for learning model training
 */
export interface LearningModelConfig {
  model_type: LearningModel["model_type"];
  training_window_days: number;
  min_samples: number;
  auto_retrain: boolean;
  retrain_interval_hours: number;
  confidence_threshold: number;
}

/**
 * Context propagation data structure
 * Used to pass context through agent handoffs and workflow executions
 */
export interface ContextPropagation {
  execution_id: string;
  workflow_id: string;
  current_task: string;
  entities: Entity[];
  accumulated_knowledge: Record<string, unknown>;
  suggestions: LearningModelSuggestion[];
  timestamp: string;
}

/**
 * Memory persistence options
 */
export interface MemoryPersistenceConfig {
  storage_path: string;
  auto_save: boolean;
  save_interval_ms: number;
  max_entity_age_days: number;
  max_history_records: number;
  enable_compression: boolean;
}
