#!/bin/bash

# Screenshot Creation Helper Script for Chrome Extension
# This script provides step-by-step instructions for creating required screenshots
# for Chrome Web Store submission

set -e

echo "=============================================="
echo "Chrome Extension Screenshot Creation Helper"
echo "=============================================="
echo ""
echo "This script will guide you through creating the 5 required screenshots"
echo "for Chrome Web Store submission."
echo ""

# Create directory
SCREENSHOT_DIR="docs/screenshots/chrome-web-store"
mkdir -p "$SCREENSHOT_DIR"
echo "✅ Created directory: $SCREENSHOT_DIR"
echo ""

# Check if extension is built
if [ ! -d "build/chrome-extension-enterprise" ]; then
    echo "⚠️  Extension not built. Building now..."
    npm run build:chrome:enterprise
else
    echo "✅ Extension build found"
fi
echo ""

echo "=============================================="
echo "STEP 1: Load Extension in Chrome"
echo "=============================================="
echo ""
echo "1. Open Google Chrome"
echo "2. Navigate to: chrome://extensions/"
echo "3. Enable 'Developer mode' (toggle in top-right)"
echo "4. Click 'Load unpacked'"
echo "5. Select folder: $(pwd)/build/chrome-extension-enterprise"
echo "6. Extension should load with icon in toolbar"
echo ""
read -p "Press ENTER when extension is loaded..."
echo ""

echo "=============================================="
echo "STEP 2: Start Backend Server (if not running)"
echo "=============================================="
echo ""
echo "In a separate terminal, run:"
echo "  npm start"
echo ""
echo "Backend should be running on: http://localhost:3000"
echo ""
read -p "Press ENTER when backend is running (or skip if not needed)..."
echo ""

echo "=============================================="
echo "SCREENSHOT 1: Execute Tab"
echo "=============================================="
echo ""
echo "What to capture:"
echo "  - Extension popup showing Execute tab"
echo "  - Sample workflow text in textarea"
echo "  - All 4 tabs visible (Execute, Builder, Templates, History, Settings)"
echo "  - Connection status indicator"
echo "  - Execute Workflow button"
echo ""
echo "Instructions:"
echo "1. Click extension icon in Chrome toolbar"
echo "2. Ensure Execute tab is selected"
echo "3. Enter sample text in textarea:"
echo "   'Search for AI automation on Google and take a screenshot'"
echo "4. Use screenshot tool to capture extension popup"
echo "5. Save as: $SCREENSHOT_DIR/screenshot-1-execute-tab.png"
echo "6. Required size: 1280x800 pixels"
echo ""
echo "Screenshot tools:"
echo "  - macOS: Cmd+Shift+4 (then select area)"
echo "  - Windows: Windows+Shift+S"
echo "  - Linux: Built-in screenshot tool"
echo "  - Chrome: DevTools > More tools > Capture screenshot"
echo ""
read -p "Press ENTER when screenshot 1 is saved..."
echo ""

echo "=============================================="
echo "SCREENSHOT 2: Workflow Builder"
echo "=============================================="
echo ""
echo "What to capture:"
echo "  - Visual workflow builder in full browser window"
echo "  - Drag-and-drop node editor"
echo "  - Sample workflow with connected nodes"
echo "  - Zoom/pan controls"
echo "  - Save/Export buttons"
echo ""
echo "Instructions:"
echo "1. Click extension icon"
echo "2. Click 'Builder' tab"
echo "3. Click 'Open Builder' button"
echo "4. Workflow builder opens in new tab"
echo "5. Create sample workflow:"
echo "   - Add 'Navigate' node"
echo "   - Add 'Click' node"
echo "   - Add 'Extract Data' node"
echo "   - Connect nodes with lines"
echo "6. Capture full browser window"
echo "7. Save as: $SCREENSHOT_DIR/screenshot-2-workflow-builder.png"
echo "8. Required size: 1280x800 pixels"
echo ""
read -p "Press ENTER when screenshot 2 is saved..."
echo ""

echo "=============================================="
echo "SCREENSHOT 3: Template Library"
echo "=============================================="
echo ""
echo "What to capture:"
echo "  - Extension popup showing Templates tab"
echo "  - Multiple workflow templates visible"
echo "  - Template cards with names and descriptions"
echo "  - Category badges"
echo ""
echo "Instructions:"
echo "1. Click extension icon"
echo "2. Click 'Templates' tab"
echo "3. Scroll to show variety of templates"
echo "4. Capture popup with 4-6 templates visible"
echo "5. Save as: $SCREENSHOT_DIR/screenshot-3-templates.png"
echo "6. Required size: 1280x800 pixels"
echo ""
read -p "Press ENTER when screenshot 3 is saved..."
echo ""

echo "=============================================="
echo "SCREENSHOT 4: Execution History"
echo "=============================================="
echo ""
echo "What to capture:"
echo "  - Extension popup showing History tab"
echo "  - Multiple completed workflow executions"
echo "  - Status badges (success, error, running)"
echo "  - Timestamps"
echo "  - Clear All button"
echo ""
echo "Instructions:"
echo "1. First, execute 3-4 workflows to populate history"
echo "   (Go to Execute tab and run some workflows)"
echo "2. Click extension icon"
echo "3. Click 'History' tab"
echo "4. Capture popup showing execution history"
echo "5. Save as: $SCREENSHOT_DIR/screenshot-4-history.png"
echo "6. Required size: 1280x800 pixels"
echo ""
read -p "Press ENTER when screenshot 4 is saved..."
echo ""

echo "=============================================="
echo "SCREENSHOT 5: Settings Panel"
echo "=============================================="
echo ""
echo "What to capture:"
echo "  - Extension popup showing Settings tab"
echo "  - Backend URL configuration field"
echo "  - Poll interval setting"
echo "  - Auto-retry toggle"
echo "  - Connection status indicator (green = connected)"
echo "  - Save Settings button"
echo ""
echo "Instructions:"
echo "1. Click extension icon"
echo "2. Click 'Settings' tab"
echo "3. Ensure Backend URL shows: http://localhost:3000"
echo "4. Show configured settings"
echo "5. Capture popup with all settings visible"
echo "6. Save as: $SCREENSHOT_DIR/screenshot-5-settings.png"
echo "7. Required size: 1280x800 pixels"
echo ""
read -p "Press ENTER when screenshot 5 is saved..."
echo ""

echo "=============================================="
echo "SCREENSHOT VERIFICATION"
echo "=============================================="
echo ""
echo "Checking screenshots..."
echo ""

# Check if screenshots exist
SCREENSHOTS_FOUND=0
REQUIRED_SCREENSHOTS=(
    "screenshot-1-execute-tab.png"
    "screenshot-2-workflow-builder.png"
    "screenshot-3-templates.png"
    "screenshot-4-history.png"
    "screenshot-5-settings.png"
)

for screenshot in "${REQUIRED_SCREENSHOTS[@]}"; do
    if [ -f "$SCREENSHOT_DIR/$screenshot" ]; then
        SIZE=$(du -h "$SCREENSHOT_DIR/$screenshot" | cut -f1)
        echo "✅ Found: $screenshot ($SIZE)"
        SCREENSHOTS_FOUND=$((SCREENSHOTS_FOUND + 1))
    else
        echo "❌ Missing: $screenshot"
    fi
done

echo ""
echo "Screenshots found: $SCREENSHOTS_FOUND / 5"
echo ""

if [ $SCREENSHOTS_FOUND -eq 5 ]; then
    echo "=============================================="
    echo "✅ ALL SCREENSHOTS CREATED!"
    echo "=============================================="
    echo ""
    echo "Next steps:"
    echo "1. Verify each screenshot is 1280x800 or 640x400 pixels"
    echo "2. Verify each file is < 2 MB"
    echo "3. Review for clarity and professionalism"
    echo "4. Upload to Chrome Web Store Developer Dashboard"
    echo ""
    echo "Screenshot location: $SCREENSHOT_DIR"
    echo ""
else
    echo "=============================================="
    echo "⚠️  INCOMPLETE - Please create missing screenshots"
    echo "=============================================="
    echo ""
    echo "Missing screenshots will prevent Chrome Web Store submission."
    echo "Please follow the instructions above to create all 5 screenshots."
    echo ""
fi

echo "For detailed guidance, see: docs/CHROME_WEB_STORE_SCREENSHOTS.md"
echo ""
echo "Done!"
